name: amochat
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  image_picker: ^0.8.5
  firebase_storage: ^10.2.13
  dash_chat_2: ^0.0.6
  enume_generator: ^1.0.3
  photo_view: ^0.13.0
  firebase_messaging: ^11.4.0
  alan_voice: ^3.5.0
  audioplayers: ^1.0.0
  just_audio: ^0.9.24

 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
    - images/logo.png


